#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

NIXCFG="$HOME/nixcfg"
SECRETS_DIR=/etc/secrets

banner "OCI → NixOS 切换向导（NIXOS_LUSTRATE）"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "前置检查"
say "确认切换前提条件，并预热 sudo。"
sudo true
[[ -d "$NIXCFG/hosts/oci" ]] || { warn "找不到 $NIXCFG/hosts/oci，中止。"; exit 1; }
if [[ -e /etc/NIXOS ]]; then
  warn "/etc/NIXOS 已存在 —— 看起来 lustrate 已标记过（可能是重跑）。"
  confirm "继续？" || exit 1
fi
[[ -f /etc/systemd/system/cloudflared.service ]] \
  || warn "没找到 cloudflared.service（token 提取阶段需要手动粘贴）。"
say "/boot 空间："
df -h /boot /boot/efi | sed 's/^/    /'
note "NixOS 每代内核+initrd ≈ 90M，需 /boot 至少有 ~200M 可用。"
say "校验配置：lustrate 依赖脚本版 stage-1（上次失败根因）……"
ISD=$(cd "$NIXCFG" && nix eval .#nixosConfigurations.oci.config.boot.initrd.systemd.enable 2>/dev/null | tr -d '[:space:]')
if [[ "$ISD" != "false" ]]; then
  warn "boot.initrd.systemd.enable 必须为 false，否则 NIXOS_LUSTRATE 不会执行！中止。"
  exit 1
fi
ISR=$(cd "$NIXCFG" && nix eval .#nixosConfigurations.oci.config.boot.loader.grub.efiInstallAsRemovable 2>/dev/null | tr -d '[:space:]')
if [[ "$ISR" != "true" ]]; then
  warn "grub.efiInstallAsRemovable 必须为 true（OCI NVRAM 不可靠）！中止。"
  exit 1
fi
say "✓ stage-1 为脚本版且 GRUB 装固件回退路径"
warn "家目录 19G 若未做异地备份，现在是最后机会（Ctrl-C 退出去备份）。"
pause

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "OCI 启动卷全量备份（整机回滚兜底）"
open_url "https://cloud.oracle.com/block-storage/boot-volumes"
step "找到本实例的启动卷 → Boot volume backups → Create boot volume backup。"
step "类型选 Full（完整备份），等状态变为 Available。"
note "若已有可用的旧备份且数据无差异，可直接确认跳过。"
note "起不来时可用它恢复整机回到 Ubuntu，这是最重要的兜底。"
confirm "备份已创建且状态 Available？" || { warn "没有备份不建议继续。"; exit 1; }

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "OCI 串口控制台实测（唯一救援通道）"
open_url "https://cloud.oracle.com/compute/instances"
step "进入本实例详情 → Resources → Console connection → Launch Cloud Shell connection。"
step "看到串口输出后，用 ubuntu 用户名+密码登录一次确认可用（NixOS 侧也保留了 ttyAMA0）。"
note "首次重启如果卡住，就靠它看内核日志、进紧急 shell。"
confirm "串口控制台已实测可登录？" || { warn "救援通道未验证不建议继续。"; exit 1; }

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "秘密文件落盘 $SECRETS_DIR"
say "写入 cloudflared token 和 ubuntu/root 密码哈希（lustrate 白名单会保留该目录）。"
sudo mkdir -p "$SECRETS_DIR"
sudo chmod 700 "$SECRETS_DIR"

# cloudflared token：优先从现有 unit 自动提取
TOKEN=$(sudo sed -n 's/.*--token \([^ ]*\).*/\1/p' /etc/systemd/system/cloudflared.service 2>/dev/null || true)
if [[ -z "$TOKEN" ]]; then
  warn "未能自动提取 token，请手动粘贴（Cloudflare Zero Trust → Tunnels → token）。"
  ask_secret TOKEN "粘贴 tunnel token:"
fi
printf 'TUNNEL_TOKEN=%s\n' "$TOKEN" | sudo tee "$SECRETS_DIR/cloudflared.env" >/dev/null
sudo chmod 600 "$SECRETS_DIR/cloudflared.env"
say "✓ 已写 $SECRETS_DIR/cloudflared.env"

# ubuntu 密码哈希：沿用 /etc/shadow 现有哈希；若被 cloud-init 锁定（前缀 !），
# 去掉前缀即可复原原密码（仅串口救援登录用，NixOS 下 sudo 已免密）
UHASH=$(sudo awk -F: '$1=="ubuntu"{print $2}' /etc/shadow)
UHASH=${UHASH#!}
if [[ "$UHASH" == \$* ]]; then
  printf '%s\n' "$UHASH" | sudo tee "$SECRETS_DIR/ubuntu.hash" >/dev/null
  say "✓ ubuntu 沿用原密码哈希（已去锁），串口可用原密码登录"
else
  warn "ubuntu 无可用密码哈希，设一个新的（仅串口救援登录用）。"
  ask_secret UBUNTU_PW "输入 ubuntu 新密码:"
  printf '%s' "$UBUNTU_PW" | openssl passwd -6 -stdin | sudo tee "$SECRETS_DIR/ubuntu.hash" >/dev/null
  unset UBUNTU_PW
fi

# root 密码哈希：串口救援登录用
say "为 root 设一个密码（仅串口控制台救援登录用，ssh 已禁 root）。"
ask_secret ROOT_PW "输入 root 密码:"
printf '%s' "$ROOT_PW" | openssl passwd -6 -stdin | sudo tee "$SECRETS_DIR/root.hash" >/dev/null
unset ROOT_PW
sudo sh -c "chmod 600 '$SECRETS_DIR'/*.hash"   # 通配符须由 root shell 展开（目录 700）
say "✓ 密码哈希已写入"
pause

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "构建 NixOS 并设为 system profile"
cd "$NIXCFG"
command -v jj >/dev/null 2>&1 && jj st >/dev/null 2>&1 || true
say "构建 toplevel（多为缓存命中）……"
nix build .#nixosConfigurations.oci.config.system.build.toplevel -o result-nixos
SYSTEM=$(readlink -f result-nixos)
say "system 闭包: $SYSTEM"
NIXBIN=/nix/var/nix/profiles/default/bin
sudo "$NIXBIN/nix-env" --profile /nix/var/nix/profiles/system --set "$SYSTEM" \
  || sudo "$NIXBIN/nix" build --extra-experimental-features 'nix-command flakes' \
       --profile /nix/var/nix/profiles/system "$SYSTEM"
say "✓ /nix/var/nix/profiles/system → $(readlink -f /nix/var/nix/profiles/system)"
pause

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "停业务服务 + 让位旧 quadlet 文件"
say "停容器和 cloudflared（重启后由 NixOS 拉起）。"
systemctl --user stop dufs sillytavern wakapi 2>/dev/null || true
systemctl --user disable podman-auto-update.timer 2>/dev/null || true
sudo systemctl stop cloudflared 2>/dev/null || true
say "把旧 .container 文件移到 systemd.pre-nixos/（新系统由 home-manager 生成同名文件）。"
mkdir -p "$HOME/.config/containers/systemd.pre-nixos"
mv "$HOME"/.config/containers/systemd/*.container \
   "$HOME/.config/containers/systemd.pre-nixos/" 2>/dev/null || true
note "如中途放弃切换，把文件移回去再 systemctl --user start 即可恢复。"
pause

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Lustrate 标记 + 清理 /boot + 安装引导【不可逆】"
warn "此步之后 Ubuntu 引导即被移除，只能前进（或用启动卷备份回滚）。"
confirm "确定执行？" || { warn "已中止，未做任何不可逆操作。"; exit 1; }

sudo touch /etc/NIXOS
printf 'etc/nixos\netc/ssh\netc/secrets\n' | sudo tee /etc/NIXOS_LUSTRATE >/dev/null
say "✓ lustrate 标记完成（白名单: etc/nixos etc/ssh etc/secrets）"

say "备份旧 /boot 与 ESP 到 /old-boot-backup（重启后随旧根进 /old-root）……"
sudo mkdir -p /old-boot-backup/boot /old-boot-backup/efi
sudo find /boot -mindepth 1 -maxdepth 1 ! -name efi ! -name 'lost+found' \
  -exec cp -a -t /old-boot-backup/boot {} +
sudo cp -a /boot/efi/EFI /old-boot-backup/efi/ 2>/dev/null || true

say "清空 /boot 与 ESP……"
sudo find /boot -mindepth 1 -maxdepth 1 ! -name efi ! -name 'lost+found' -exec rm -rf {} +
sudo rm -rf /boot/efi/EFI

say "安装 NixOS 引导（GRUB EFI）……"
sudo NIXOS_INSTALL_BOOTLOADER=1 /nix/var/nix/profiles/system/bin/switch-to-configuration boot

say "校验结果："
sudo ls /boot | sed 's/^/    /'
sudo ls /boot/efi/EFI 2>/dev/null | sed 's/^/    /'
# ESP 挂载 umask=0077，校验必须以 root 进行
if ! sudo test -f /boot/efi/EFI/BOOT/BOOTAA64.EFI; then
  warn "缺 /boot/efi/EFI/BOOT/BOOTAA64.EFI（固件回退引导）！勿重启！"
  exit 1
fi
if ! sudo test -f /boot/grub/grub.cfg; then
  warn "缺 /boot/grub/grub.cfg！勿重启！"
  exit 1
fi
say "✓ EFI 回退引导与 grub.cfg 就位"
step "确认上面能看到 NixOS 的内核与 grub 目录。"
confirm "引导安装看起来正常？" || { warn "请勿重启！用 /old-boot-backup 手动恢复或求助。"; exit 1; }

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "重启进入 NixOS"
say "重启后首次启动会执行 lustrate：旧 Ubuntu 根移入 /old-root，"
say "@home/@containers 子卷原样保留。"
step "另开 OCI 串口控制台窗口盯着启动日志。"
say ""
say "重启后的验证清单："
note "  ssh ubuntu@<ip> 直连；容器: systemctl --user status dufs sillytavern wakapi"
note "  cloudflared: systemctl status cloudflared；隧道服务外部可达"
note "  nix profile list 用户包还在；sudo 密码可用"
say ""
say "稳定后清理：sudo rm -rf /old-root；efibootmgr 删 ubuntu 项。"
confirm "现在重启？" || { say "可稍后手动 sudo reboot。"; exit 0; }
sudo reboot
